[package]
name    = "tile_governance"
version = "0.1.0"
edition = "2024"

[addresses]
tile_governance = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
